#!/bin/bash

if [ ! -f "pyproject.toml" ]; then
 if [ -d "$ENV_PATH" ]; then
     rm -rf $ENV_PATH
     echo "Removed the poetry environment at $ENV_PATH."
 else
     echo "No poetry environment found."
 fi

    echo "pyproject.toml file not found."
    exit 1
fi
 echo "Setup completed successfully."
 exit 0
